name: Setup Node.js
description: Setup Node.js

inputs:
  working-directory:
    description: The working directory to install dependencies in
    required: true
    default: '.'

runs:
  using: composite
  steps:
    - name: Enable Corepack
      run: corepack enable
      shell: bash

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'yarn'

    - name: Install and build
      working-directory: ${{ inputs.working-directory }}
      run: yarn install --immutable
      shell: bash